{
  lib',
  inputs,
  config,
  ...
}:
let
  inherit (lib'.lab) mkHostOptions mkHostPlatform;
  inherit (lib')
    mkDefault
    mkOption
    mapAttrs
    filterAttrs
    types
    ;

  # Apply the host's single home-manager configuration to its user.
  homeManager = host: {
    home-manager = {
      useGlobalPkgs = true;
      useUserPackages = true;
      users.${host.user} =
        { osConfig, ... }:
        {
          imports = [ host.asahi.home ];
          home.stateVersion = mkDefault osConfig.system.stateVersion;
          programs.home-manager.enable = false;
        };
    };
  };

  # Base configuration shared with nixos.nix. Asahi uses the pinned
  # nixos-apple-silicon nixpkgs and does NOT enable allowUnfree.
  base = {
    imports = [
      inputs.nixos-apple-silicon.nixosModules.apple-silicon-support
      inputs.home-manager-asahi.nixosModules.home-manager
    ];

    i18n = {
      defaultLocale = "en_US.UTF-8";
      extraLocaleSettings = {
        LC_ADDRESS = "en_US.UTF-8";
        LC_IDENTIFICATION = "en_US.UTF-8";
        LC_MEASUREMENT = "en_US.UTF-8";
        LC_MONETARY = "en_US.UTF-8";
        LC_NAME = "en_US.UTF-8";
        LC_NUMERIC = "en_US.UTF-8";
        LC_PAPER = "en_US.UTF-8";
        LC_TELEPHONE = "en_US.UTF-8";
        LC_TIME = "en_US.UTF-8";
      };
    };

    nix.settings.experimental-features = "nix-command flakes";

    nixpkgs = {
      config = {
        allowUnfree = true;
        permittedInsecurePackages = [
          "libsoup-2.74.3"
        ];
      };
      overlays = [ (import ../overlay.nix inputs) ];
    };

    # stateVersion is stateful — pin to the host's install version (25.05),
    # independent of the pinned 25.11 nixpkgs.
    system.stateVersion = mkDefault "25.05";
    time.timeZone = "America/New_York";
  };
in
{
  options = {
    lab = {
      hosts = mkHostOptions {
        asahi = mkHostPlatform (
          { config, ... }:
          let
            asahi = config;
          in
          {
            options = {
              specialArgs = mkOption {
                type = types.attrsOf types.anything;
                default = { };
              };

              home = mkOption {
                description = "Home-manager configuration for this platform's user";
                type = types.deferredModule;
                default = { };
              };

              peripheralFirmwareHash = mkOption {
                type = types.str;
                default = abort ''

                  No peripheral firmware hash set.
                  ---------------------------------------------------------------------------------
                  1. Run `nix-hash --type sha256 --to-sri $(nix-hash --type sha256 --base32 $(nix-store --add-fixed sha256 /boot/asahi/ --recursive))` on the target machine.
                  2. Set 'lab.hosts.{host}.asahi.peripheralFirmwareHash' to the sha256 hash generated by the above command.
                  ---------------------------------------------------------------------------------
                '';
              };
            };

            config = {
              module =
                { pkgs, ... }:
                {
                  imports = [ base ];

                  boot = {
                    # For ` to < and ~ to > (for those with US keyboards)
                    extraModprobeConfig = ''
                      options hid_apple iso_layout=0
                    '';

                    initrd = {
                      availableKernelModules = [
                        "usb_storage"
                        "sdhci_pci"
                      ];
                    };

                    # Extend display to notch
                    kernelParams = [
                      "apple_dcp.show_notch=1"
                    ];

                    # Use the systemd-boot EFI boot loader.
                    loader = {
                      systemd-boot.enable = true;
                      efi.canTouchEfiVariables = false;
                    };
                  };

                  hardware.asahi.peripheralFirmwareDirectory = mkDefault (
                    pkgs.requireFile {
                      name = "asahi";
                      url = "file:///boot/asahi";
                      hashMode = "recursive";
                      sha256 = asahi.peripheralFirmwareHash;
                    }
                  );
                };
            };
          }
        );
      };
    };
  };

  config = {
    flake = {
      nixosConfigurations = mapAttrs (
        _: host:
        inputs.nixos-apple-silicon.inputs.nixpkgs.lib.nixosSystem {
          system = "aarch64-linux";
          specialArgs = host.asahi.specialArgs;
          modules = [
            host.asahi.module
            (homeManager host)
          ];
        }
      ) (filterAttrs (_: host: host.asahi.eval) config.lab.hosts);

      nixosModules = mapAttrs (_: host: {
        imports = [
          host.asahi.module
          (homeManager host)
        ];
      }) (filterAttrs (_: host: host.asahi.enable) config.lab.hosts);
    };
  };
}
