{
  lib',
  inputs,
  config,
  ...
}:
let
  inherit (lib'.lab) mkHostOptions mkHostPlatform;
  inherit (lib')
    mkDefault
    mkOption
    mapAttrs
    filterAttrs
    types
    ;
in
{
  options = {
    lab = {
      hosts = mkHostOptions {
        asahi = mkHostPlatform (
          { config, ... }:
          let
            asahi = config;
          in
          {
            options = {
              peripheralFirmwareHash = mkOption {
                type = types.str;
                default = abort ''

                  No peripheral firmware hash set.
                  ---------------------------------------------------------------------------------
                  1. Run `nix-hash --type sha256 --to-sri $(nix-hash --type sha256 --base32 $(nix-store --add-fixed sha256 /boot/asahi/ --recursive))` on the target machine.
                  2. Set 'lab.hosts.{host}.asahi.peripheralFirmwareHash' to the sha256 hash generated by the above command.
                  ---------------------------------------------------------------------------------
                '';
              };
            };

            config = {
              eval = mkDefault true;
              module =
                { pkgs, ... }:
                {
                  boot = {
                    # For ` to < and ~ to > (for those with US keyboards)
                    extraModprobeConfig = ''
                      options hid_apple iso_layout=0
                    '';

                    initrd = {
                      availableKernelModules = [
                        "usb_storage"
                        "sdhci_pci"
                      ];
                    };

                    # Extend display to notch
                    kernelParams = [
                      "apple_dcp.show_notch=1"
                    ];

                    # Use the systemd-boot EFI boot loader.
                    loader = {
                      systemd-boot.enable = true;
                      efi.canTouchEfiVariables = false;
                    };
                  };

                  hardware.asahi.peripheralFirmwareDirectory = mkDefault (
                    pkgs.requireFile {
                      name = "asahi";
                      url = "file:///boot/asahi";
                      hashMode = "recursive";
                      sha256 = asahi.peripheralFirmwareHash;
                    }
                  );
                };
            };
          }
        );
      };
    };
  };

  config = {
    flake = {
      nixosConfigurations = mapAttrs (
        _: host:
        inputs.nixos-apple-silicon.inputs.nixpkgs.lib.nixosSystem {
          system = "aarch64-linux";
          specialArgs = host.asahi.specialArgs;
          modules = [ host.asahi.module ];
        }
      ) (filterAttrs (_: host: host.asahi.eval) config.lab.hosts);

      nixosModules = mapAttrs (_: host: host.asahi.module) (
        filterAttrs (_: host: host.asahi.enable) config.lab.hosts
      );
    };
  };
}
