if [ -f /etc/zshrc ] && ! command -v nix > /dev/null 2> /dev/null; then
  source /etc/zshrc
fi

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

if [[ -e ~/.local/state/nix/profiles/home-manager/share/zsh-powerlevel10k/powerlevel9k.zsh-theme ]]; then
  . ~/.local/state/nix/profiles/home-manager/share/zsh-powerlevel10k/powerlevel9k.zsh-theme
elif [[ -e ~/.nix-profile/share/zsh-powerlevel10k/powerlevel9k.zsh-theme ]]; then
  . ~/.nix-profile/share/zsh-powerlevel10k/powerlevel9k.zsh-theme
fi
