[book]
title = "jmoo/lab"
authors = ["John Moore"]
description = "NixOS / nix-darwin configuration for jmoo's machines"
language = "en"
src = "src"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/jmoo/lab"
edit-url-template = "https://github.com/jmoo/lab/edit/master/docs/{path}"
